#tomcat配置
server:
  max-http-header-size: 8192
  #tomcat端口
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    max-connections: 1000
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    # tomcat最大线程数，默认为200
    max-threads: 1500
    #tomcat配置参数编码
    uri-encoding: UTF-8

spring:
  profiles:
    # 配置数据源db-sqlserver / db-mysql
    include: db-sqlserver

  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    prefix: classpath:/templates/
    # 是否启用缓存
    cache: false

  #热部署
  devtools:
    restart:
      #热部署生效 true|false
      enabled: true
      #设置重启的目录，检索目录(resources/static、resources/templates)
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

  #redis单机配置,本处只使用单机redis版本
  redis:
    host: 127.0.0.1
    port: 6379
    #默认db=0
    database: 0
    # 密码（默认为空）
    password:
    # 连接超时时长（毫秒）
    timeout: 6000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10
        # 连接池中的最大空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000


#是否开启swagger接口页面，true|false
swagger:
  open: true

#是否开启通用日志打印
auto:
  log:
    # 是否输出请求信息
    enabled: true

# 日志配置
logging:
  level:
    com.afeng: debug
    org.springframework: warn

